### ISSUE TITLE
triggerPattern not working anymore

### ISSUE THREAD

**Issue by sgelb** [fannheyward/create-coc-extension#131]
Hello,

since https://github.com/neoclide/coc.nvim/commit/0ff4c24748b6cf392d1036979a471c9c05028f27, using triggerPattern in a created extension does not work anymore.

To reproduce
- run `create-coc-extension test`
- change the empty triggerPattern in test/src/index.ts to `triggerPatterns: [/Test/]` 
- add `enable: true`
- add `set runtimepath^=/path/to/test` to init.vim
- run `yarn build`

Before https://github.com/neoclide/coc.nvim/commit/0ff4c24748b6cf392d1036979a471c9c05028f27, after typing `Test` I could complete to `TestCompletionItem 1` and `TestCompletionItem 2`. After that commit, nothing happens.

Is this a problem of create-coc-extension or of coc.nvim?

**Comment by fannheyward** [comment]
If you defined `triggerPatterns`, coc will consider this source is `triggerOnly`, https://github.com/neoclide/coc.nvim/blob/d3048fd4badd3fdf9eb34153bcac29a4a5900123/src/model/source.ts#L36.

Test with this: `coc#refresh()` to refresh completion without input `Test`, this source will available.

**Comment by sgelb** [comment]
Hello,

perhaps I did not describe my problem thorough enough. After typing `Test`, it would automatically provide an popup with the suitable completions. After the commit, this does not happen anymore, `coc#refresh()` does not change anything. It looks exactly like the problem describes in https://github.com/neoclide/coc.nvim/issues/2032. You mentioned a "triggerPatterns regex issue". 

I will experiment a bit more.

**Comment by fannheyward** [comment]
You can get completion suggestions after you type `Test.`.
