### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by voldikss** [fannheyward/create-coc-extension#14]
- [x] Initialize a git repository for the extension 
- [x] Automatically execute `npm install` or `yarn install` after creating
<del>- [ ] Use better prompting UI (see https://github.com/fannheyward/create-coc-extension/issues/14#issuecomment-527156883)</del>
- [x] Multiple extension types
<del>    - [ ] New Extension (JavaScript)</del>
    - [x] New Extension (TypeScript) (already exists)
- [x] More extension components
    - [x] New Keymap
    - [x] New Autocmd
    - [x] New Command (already exists)
    - [x] New Code Completion Source (already exists)
    - [x] New LSP Extension
    - [x] Explain demo code in comments
<del>- [ ] ASCII graph (see https://github.com/fannheyward/create-coc-extension/issues/14#issuecomment-527156883)</del>

**Comment by voldikss** [comment]
大佬有空考虑下上面的这些 feature 吗

**Comment by oblitum** [comment]
Is it interesting/possible to have a feature of importing a vscode extension into a coc-extension?

**Comment by rashil2000** [comment]
> Is it interesting/possible to have a feature of importing a vscode extension into a coc extension? For easy migration.

Was this pursued? I'd like to create a coc extension from [this](https://github.com/RechInformatica/rech-editor-batch) VSCode extension...

**Comment by voldikss** [comment]
@rashil2000 You may open another issue. Now that the features has been added as expected, I think this issue should be closed.
