### ISSUE TITLE
How can I connect to the lsp using socket?

### ISSUE THREAD

**Issue by dagyu** [fannheyward/create-coc-extension#190]
Hi i can't figure out how I can connect to my lsp using sockets. 

For the vscode client I used the same code of this https://github.com/microsoft/vscode-languageserver-node/issues/662#issuecomment-678643225 that works for me. I tried to use the same code for the con client but nothing happens to me and I don't know how to find any logs.

**Could you help me somehow**? It would be of great help to me to debug my lsp.

**Comment by fannheyward** [comment]
Sorry for the delay. Check the tests code https://github.com/neoclide/coc.nvim/blob/03c9add7cd867a013102dcb45fb4e75304d227d7/src/__tests__/client/integration.test.ts#L108-L118.

**Comment by fannheyward** [comment]
I didn't test the socket LSP, do you know any LS that supports socket connection, I can make a test.
